POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxpb251c2VybmFtZSIsImlkIjoiNjdlOTVmMTNkN2ViYzI3ZGM0YmY1MDUxIiwiaWF0IjoxNzQzMzUyMTU2fQ.Wuye2Jpsff-FfNAEXwE03ZfuTlCEVo5jgSnScPLp8a4

{
  "title": "Testblog2",
  "author": "cat",
  "url": "www.cats.org"
}
