DELETE http://localhost:3001/api/users/67e9731f9dcf8fc35c3cb412
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxpb251c2VybmFtZSIsImlkIjoiNjdlOTVmMTNkN2ViYzI3ZGM0YmY1MDUxIiwiaWF0IjoxNzQzMzUyMjM5fQ.1lMX1hq75-2pypjIar79efolVAaYORTnzPP9YD-df3s
