DELETE http://localhost:3001/api/blogs/67e6887861d0f4d2a5447aa7
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhdHVzZXJuYW1lIiwiaWQiOiI2N2U4Y2E2MGYzMzNhMWMzZGQzMzk1MTYiLCJpYXQiOjE3NDMzMDk0MTd9.UXJHKP81jZsKwspU-hywL5j7aXrsy8ogQTL_j7sWNX4
