DELETE http://localhost:3001/api/blogs/67e9717d72ea93b120a9c9a2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxpb251c2VybmFtZSIsImlkIjoiNjdlOTVmMTNkN2ViYzI3ZGM0YmY1MDUxIiwiaWF0IjoxNzQzMzUyMjM5fQ.1lMX1hq75-2pypjIar79efolVAaYORTnzPP9YD-df3s
