POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvZ3VzZXJuYW1lIiwiaWQiOiI2N2U2YTc4MDVkYjgyNTllMjI1OTUwOWIiLCJpYXQiOjE3NDMxNjk2NDZ9.NhvqDFqxAP4mumUlnXxhR_AfpxcKQYZX8H9RM1t-Ulw

{
  "title": "Testblog2",
  "author": "cat",
  "url": "www.cats.org"
}
